version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_sri
    restart: always
    environment:
      POSTGRES_USER: el19160
      POSTGRES_PASSWORD: pr5td!z386
      POSTGRES_DB: sri_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./sri-backend
    container_name: sri_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://el19160:pr5td!z386@postgres:5432/sri_db
    ports:
      - "8000:8000"
    volumes:
      - ./sri-backend:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build: ./sri-frontend
    container_name: sri_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./sri-frontend:/app
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:8000"

volumes:
  postgres_data: