"""Add region to Building model

Revision ID: 91c3554c6a15
Revises: 644a49cba9a3
Create Date: 2024-09-06 11:50:18.142821+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '91c3554c6a15'
down_revision: Union[str, None] = '644a49cba9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('building', sa.Column('street', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('building', sa.Column('zip', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('building', 'building_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('building', 'building_usage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('building', 'building_state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('building', 'energy_class',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('building', 'year',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building', 'year',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('building', 'energy_class',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('building', 'building_state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('building', 'building_usage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('building', 'building_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('building', 'zip')
    op.drop_column('building', 'street')
    op.drop_column('building', 'region')
    # ### end Alembic commands ###
