"""Add domains to Building model

Revision ID: f7dce580baad
Revises: 1dcbb9c8666d
Create Date: 2024-07-17 09:45:39.423338+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7dce580baad'
down_revision: Union[str, None] = '1dcbb9c8666d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serviceselection')
    op.drop_table('sriinput')
    op.drop_table('buildingdomainlink')
    op.add_column('building', sa.Column('domains', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('building', 'building_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building', 'building_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('building', 'domains')
    op.create_table('buildingdomainlink',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], name='buildingdomainlink_building_id_fkey'),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], name='buildingdomainlink_domain_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='buildingdomainlink_pkey')
    )
    op.create_table('sriinput',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], name='sriinput_building_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sriinput_pkey')
    )
    op.create_table('domain',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='domain_pkey')
    )
    op.create_table('serviceselection',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], name='serviceselection_building_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='serviceselection_pkey')
    )
    # ### end Alembic commands ###
