"""Add sri_scores to Building model

Revision ID: 531254aeb790
Revises: f7dce580baad
Create Date: 2024-07-17 18:09:40.077476+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '531254aeb790'
down_revision: Union[str, None] = 'f7dce580baad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domain')
    op.add_column('building', sa.Column('sri_scores', sa.JSON(), nullable=True))
    op.add_column('building', sa.Column('total_sri', sa.Float(), nullable=True))
    op.alter_column('building', 'building_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building', 'building_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('building', 'total_sri')
    op.drop_column('building', 'sri_scores')
    op.create_table('domain',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='domain_pkey')
    )
    # ### end Alembic commands ###
