"""Add energy_class to Building model

Revision ID: 644a49cba9a3
Revises: c64a24671d45
Create Date: 2024-09-06 11:39:25.459313+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '644a49cba9a3'
down_revision: Union[str, None] = 'c64a24671d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('energy_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('building', 'building_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('building', 'building_usage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('building', 'building_state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('building', 'year',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building', 'year',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('building', 'building_state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('building', 'building_usage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('building', 'building_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('building', 'energy_class')
    # ### end Alembic commands ###
