"""Add building_name to Building model

Revision ID: 1dcbb9c8666d
Revises: e7d6d985752c
Create Date: 2024-07-12 18:37:04.330133+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1dcbb9c8666d'
down_revision: Union[str, None] = 'e7d6d985752c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('building_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('building', 'building_name')
    op.create_table('buildingdomainlink',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], name='buildingdomainlink_building_id_fkey'),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], name='buildingdomainlink_domain_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='buildingdomainlink_pkey')
    )
    # ### end Alembic commands ###
