"""Add year to Building model

Revision ID: b363148eaa5b
Revises: ecf91af3d4e0
Create Date: 2024-09-06 06:59:18.354424+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b363148eaa5b'
down_revision: Union[str, None] = 'ecf91af3d4e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('year', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('building', 'building_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('building', 'year_built')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('year_built', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('building', 'building_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('building', 'year')
    # ### end Alembic commands ###
