"""Add building_usage to Building model

Revision ID: 05feb41beefe
Revises: b363148eaa5b
Create Date: 2024-09-06 11:22:34.851117+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '05feb41beefe'
down_revision: Union[str, None] = 'b363148eaa5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('building_usage', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('building', 'building_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('building', 'year',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building', 'year',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('building', 'building_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('building', 'building_usage')
    # ### end Alembic commands ###
