"""Add building_state to Building model

Revision ID: c64a24671d45
Revises: 05feb41beefe
Create Date: 2024-09-06 11:33:32.251021+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c64a24671d45'
down_revision: Union[str, None] = '05feb41beefe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('building_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('building', 'building_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('building', 'building_usage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('building', 'year',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building', 'year',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('building', 'building_usage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('building', 'building_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('building', 'building_state')
    # ### end Alembic commands ###
